# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finventory.proto\"\x07\n\x05\x45mpty\"\x15\n\x07Payload\x12\n\n\x02id\x18\x01 \x01(\x05\"j\n\x0eProductRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05photo\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\"6\n\x10ProductsResponse\x12\"\n\x08products\x18\x01 \x03(\x0b\x32\x10.ProductResponse\"k\n\x0fProductResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08quantity\x18\x03 \x01(\x05\x12\r\n\x05price\x18\x04 \x01(\x02\x12\r\n\x05photo\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t2\x85\x02\n\x10InventoryService\x12\x30\n\x11SearchAllProducts\x12\x06.Empty\x1a\x11.ProductsResponse\"\x00\x12\x31\n\x11SearchProductByID\x12\x08.Payload\x1a\x10.ProductResponse\"\x00\x12\x31\n\nAddProduct\x12\x0f.ProductRequest\x1a\x10.ProductResponse\"\x00\x12\x34\n\rUpdateProduct\x12\x0f.ProductRequest\x1a\x10.ProductResponse\"\x00\x12#\n\rDeleteProduct\x12\x08.Payload\x1a\x06.Empty\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=19
  _globals['_EMPTY']._serialized_end=26
  _globals['_PAYLOAD']._serialized_start=28
  _globals['_PAYLOAD']._serialized_end=49
  _globals['_PRODUCTREQUEST']._serialized_start=51
  _globals['_PRODUCTREQUEST']._serialized_end=157
  _globals['_PRODUCTSRESPONSE']._serialized_start=159
  _globals['_PRODUCTSRESPONSE']._serialized_end=213
  _globals['_PRODUCTRESPONSE']._serialized_start=215
  _globals['_PRODUCTRESPONSE']._serialized_end=322
  _globals['_INVENTORYSERVICE']._serialized_start=325
  _globals['_INVENTORYSERVICE']._serialized_end=586
# @@protoc_insertion_point(module_scope)
